import { Geist, Geist_Mono, Montserrat } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "Montserrat,sans-serif",

  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "Montserrat",
  // weight: "300",
  subsets: ["latin"]
})
const geistMono = Geist_Mono({
  variable: "antialiased",

  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
